# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.MY_TOKEN }}
          user: ELSHIRAK
          template: classic
          base: metadata
          config_timezone: Asia/Yerevan
          plugin_languages: yes
          filename: metrics.plugin.leetcode.svg
          plugin_leetcode: yes
          plugin_leetcode_user: elshirak
          plugin_leetcode_sections: solved, skills, recent
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_limit: 9
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 4
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
